version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - nest-api.env

volumes:
  postgres:
